Fix unused but passed kwargs to peering routines
The error is:

```
TypeError: process_peering_event() got an unexpected keyword argument 'resource_indexed'
```

The kwarg is added in 1.30.0 for indexing, added as unused to all processing routines except the peering, and this was not caught in testing (both in automated and manual) — because the kwargs are unused and the peering is usually disabled in tests to not produce unnecessary logs/steps.

Signed-off-by: Sergey Vasilyev <nolar@nolar.info>